### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by lcw** [JuliaIO/LightXML.jl#101]
Could a new release, say v0.8.1, be tagged with the FreeBSD fix #100 that just got merged? Thanks!

**Comment by ianshmean** [comment]
I just:
- set up a Project.toml
- fixed a missing Libdl dep
- updated CI testing versions (1.0, 1.2, nightly)
- added CI testing for ARM & FreeBSD
- Put in a request for a new release

I'll close this when the release is published

**Comment by ararslan** [comment]
Seems this has been released as v0.8.1, so I'll go ahead and close this.
