### ISSUE TITLE
Support doctype

### ISSUE THREAD

**Issue by juliangehring** [JuliaIO/LightXML.jl#21]
LightXML does not seem to have support for setting the doctype of a document (see also https://stackoverflow.com/questions/28307079/lightxml-jl-insert-doctype for a discussion).

This feature could get integrated with the existing API, e.g.

``` julia
xdoc = XMLDocument(doctype = "doc")
```

**Comment by tkelman** [comment]
Seems like a good idea. Can you find the appropriate C API's in libxml2 to do this? I'll look over a PR if you can put one together.
