### ISSUE TITLE
Method Error for length() in Julia v0.5

### ISSUE THREAD

**Issue by paulstey** [JuliaIO/LightXML.jl#48]
I'm not sure if this is a known issue, but I didn't see it already raised. 

When using Julia v0.5 I'm getting a `MethodError` when calling `collect(child_elements(xroot))`. This fails giving the following message:
```{text}
ERROR: MethodError: no method matching length(::LightXML.XMLElementIter)
 in _similar_for at ./array.jl:209 [inlined]
 in _collect at ./array.jl:229 [inlined]
 in collect(::LightXML.XMLElementIter) at ./array.jl:225
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```
Incidentally, this error is also returned by running `Pkg.test("LightXML")`.

Again, this only seems to be an issue with Julia v0.5; there is no problem with Julia 0.4.5.

Is this a known issue? Is there an existing fix?

**Comment by tkelman** [comment]
https://github.com/JuliaIO/LightXML.jl/pull/47 may have fixed this on master, I'd have to double-check. Just haven't tagged for some time.

**Comment by paulstey** [comment]
Thanks for the quick response. You're exactly right, this is fixed on master. Thank you!
