### ISSUE TITLE
ubuntu 16.04 libxml2 troubles

### ISSUE THREAD

**Issue by jadamcak** [JuliaIO/LightXML.jl#56]
Pkg.add("LightXML") need install libxml2 manualy via sudo apt-get install libxml2-dev 

see discusion https://groups.google.com/d/topic/julia-users/BH-xHZWqItY/discussion

**Comment by freeboson** [comment]
@jadamcak I think this is pretty normal. Many python packages that wrap libraries expect you to install the library yourself as well.

**Comment by kmsquire** [comment]
In Julia, it's common to use `BinDeps.jl` to attempt to install the library for the user.  However, this might not have been very common when this package was created, and it does not seem to be very actively maintained right now.

**Comment by ararslan** [comment]
Should be fixed by #85.
