### ISSUE TITLE
Package candidate for libxml2-2 not found on julia 0.7 in windows

### ISSUE THREAD

**Issue by galenlynch** [JuliaIO/LightXML.jl#72]
Hi,

I cannot build lightxml on `Julia Version 0.7.0-DEV.235` on windows `x86_64-w64-mingw32`. I get the following error while attempting to build:
```
==============================[ ERROR: LightXML ]==========================
LoadError: Package candidate for libxml2-2 not found
while loading C:\Users\appveyor\.julia\v0.7\LightXML\deps\build.jl, in expression starting on line 4
===========================================================================
```
The output of my attempt to build it can be found [here](https://ci.appveyor.com/project/galenlynch/openephysloader-jl/build/1.0.58/job/vp4b7887w9o5wt3u#L10).

**Comment by tkelman** [comment]
looks like a download failure?

**Comment by galenlynch** [comment]
Ah you're right, sorry!
