### ISSUE TITLE
free usage should be in the first example

### ISSUE THREAD

**Issue by freeboson** [JuliaIO/LightXML.jl#75]
I was recently helping a colleague with his script that did some processing of XML files with this package. I was looking in all of the other places for why the memory usage was blowing up, before realizing it was due to not calling `free`.

I completely understand now why the memory allocated by this package cannot be garbage collected, but this is definitely an important thing to stress. It first shows up in the readme about 2/3 of the way down, but IMO it's a basic requirement for using this package. I think the very first example should make use of `free`.

**Comment by bicycle1885** [comment]
Just out of curiosity, why you don't choose EzXML.jl? It frees allocated memories automatically and I believe it covers all functionalities of LightXML.jl. I would like to know the reason to improve my package.

**Comment by freeboson** [comment]
@bicycle1885 actually, my colleague ended up using https://github.com/samoconnor/XMLDict.jl. I would use `EzXML.jl` or `XMLDict.jl`.

**Comment by bicycle1885** [comment]
Okay, thank you.

**Comment by samoconnor** [comment]
See #45
