### ISSUE TITLE
Build error with Julia 1.0

### ISSUE THREAD

**Issue by GrayJack** [JuliaIO/LightXML.jl#91]
I attached the build log so you can have a more complete log.
I'm new to julia, so I'm not sure why this is happening

[build.log](https://github.com/JuliaIO/LightXML.jl/files/2475778/build.log)

Thanks in advance

**Comment by omus** [comment]
Could you give more details like what OS you are using and if you are using the official Julia 1.0 binaries or if you have compiled Julia from source?

**Comment by GrayJack** [comment]
I'm using Manjaro Linux.
I'm now using Julia 1.0.1 from the official repositories from Manjaro.

**Comment by GrayJack** [comment]
If you need something else, please, let me know :3

**Comment by omus** [comment]
Sorry for the delayed response. I'll try to get you sorted out. Can you run the following and let me know what the output is?

```julia
using BinaryProvider
abi = BinaryProvider.detect_compiler_abi()
abi_str = BinaryProvider.compiler_abi_str(abi)
platform_str = string(Sys.MACHINE, abi_str)
platform_key_abi(platform_str)
```

The result on my machine looks like:
```julia
julia> using BinaryProvider

julia> abi = BinaryProvider.detect_compiler_abi()
CompilerABI(:gcc8, :cxx03)

julia> abi_str = BinaryProvider.compiler_abi_str(abi)
"-gcc8-cxx03"

julia> platform_str = string(Sys.MACHINE, abi_str)
"x86_64-apple-darwin17.7.0-gcc8-cxx03"

julia> platform_key_abi(platform_str)
MacOS(:x86_64, compiler_abi=CompilerABI(:gcc8, :cxx03))
```

**Comment by omus** [comment]
@staticfloat you may just know what this issue is

**Comment by staticfloat** [comment]
This looks like a `BinaryProvider` issue; the segfault you're seeing is happening during [`open_libllvm()` time](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/53dbc7c5cb94487d00da6f9d7ae6afbda7d794c5/src/PlatformNames.jl#L643-L651) within BinaryProvider.  This is often due to a Linux distribution shipping libLLVM's that are incompatible with Julia, and so if we try to `dlopen()` it, we fail miserably.

What surprises me is that you're later able to use `BinaryProvider.detect_compiler_abi()` directly; it doesn't segfault at all.  What happens if you do the following:

```julia
using Libdl
dlopen_e.(["libLLVM", "LLVM", "libLLVMSupport"])
```

**Comment by GrayJack** [comment]
That's what I get

```
3-element Array{Ptr{Nothing},1}:
 Ptr{Nothing} @0x000055fe2fef1c00
 Ptr{Nothing} @0x0000000000000000
 Ptr{Nothing} @0x0000000000000000
```

**Comment by staticfloat** [comment]
Hmmm, so nothing there should be causing a segfault then.  Perhaps there is some other package you've loaded that causes the incompatibility.  What other packages are loaded when you're trying to build LightXML?

**Comment by staticfloat** [comment]
Okay, well let us know if it happens again!  In any case, this is not a `LightXML.jl` issue, so I'm going to close this, but if it does happen again (and you can trigger it reliably) please open an issue on the [BinaryProvider.jl](https://github.com/JuliaPackaging/BinaryProvider.jl) repository.
