### ISSUE TITLE
LoadError: syntax: { } vector syntax is discontinued

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaIO/LightXML.jl#97]
I'm new to Julia and was testing your package based on the "Create new XML document" section of your README. 

However, I got this error `LoadError: syntax: { } vector syntax is discontinued` on this line: 
```julia
set_attributes(xs2, {"tag"=>"IL", "cap"=>"Springfield"})
```
I'm using Julia 1.1.1 (on Ubuntu 19.04).

**Comment by Kevin-Mattheus-Moerman** [comment]
Is appears it is just a matter of using this with square brackets instead: 
```julia
set_attributes(xs2, ["tag"=>"IL", "cap"=>"Springfield"])
```
Perhaps update the README if this is correct.

**Comment by omus** [comment]
Curly braces were previous used to create dictionaries in an early version of Julia. The modern equivalent would be:
```julia 
set_attributes(xs2, Dict("tag"=>"IL", "cap"=>"Springfield"))
```
The README should definitely be updated. 

Since you mentioned you're new to Julia you should also checkout the [EzXML.jl package](https://github.com/bicycle1885/EzXML.jl)

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks. What is the main difference between your package and EzXML? Are both maintained to the same extent? I will have to generate very large XML files (defining computational models with millions of nodes and elements). 

Below is what I currently use (with MATLAB and my [GIBBON](https://github.com/gibbonCode/GIBBON) toolbox), perhaps you can recommend a certain approach with your package: 
```matlab
febio_spec.Geometry.Nodes{1}.ATTR.name='nodeSet1';
febio_spec.Geometry.Nodes{1}.node.ATTR.id=[1 102 2]';
febio_spec.Geometry.Nodes{1}.node.VAL=randn(3,3);
```
Which translates to:
```xml
<Nodes name="nodeSet1">
      <node id="1">5.3766714e-01, 8.6217332e-01, -4.3359202e-01</node>
      <node id="102">1.8338850e+00, 3.1876524e-01, 3.4262447e-01</node>
      <node id="2">-2.2588469e+00, -1.3076883e+00, 3.5783969e+00</node>
</Nodes>
```
Note my use of ATTR and VAL to trigger attributes or value entries in the conversion from the MATLAB structure to an XML file.

**Comment by omus** [comment]
I'm not a maintainer on this package or EzXML but I've found that EzXML has been more actively maintained as of late.

If you are concerned with performance and memory allocations I would recommend making prototype implementations with both libraries and using [BenchmarkTools.jl](https://github.com/JuliaCI/BenchmarkTools.jl) to compare.

You also may want to join the [Julia Slack](https://slackinvite.julialang.org/) which will get you help and advice from the general Julia community.

**Comment by omus** [comment]
Issue can now be closed
